# --- Defaults FF-D4PG ---

system_name: ff_d4pg # Name of the system.

# --- RL hyperparameters ---
rollout_length: 1 # Number of environment steps per vectorised environment.
epochs: 1 # Number of sgd steps per rollout.
warmup_steps: 32  # Number of steps to collect before training.
total_buffer_size: 500_000 # Total effective size of the replay buffer across all devices and vectorised update steps. This means each device has a buffer of size buffer_size//num_devices which is further divided by the update_batch_size. This value must be divisible by num_devices*update_batch_size.
total_batch_size: 256 # Total effective number of samples to train on. This means each device has a batch size of batch_size/num_devices which is further divided by the update_batch_size. This value must be divisible by num_devices*update_batch_size.
actor_lr: 3e-4  # the learning rate of the policy network optimizer
q_lr: 3e-4  # the learning rate of the Q network network optimizer
tau: 0.005  # smoothing coefficient for target networks
gamma: 0.99  # discount factor
max_grad_norm: 0.5 # Maximum norm of the gradients for a weight update.
decay_learning_rates: False # Whether learning rates should be linearly decayed during training.
max_abs_reward : 20_000  # maximum absolute reward value
num_atoms: 301  # number of atoms in the distributional Q network
vmin: -9_000.0  # minimum value of the support
vmax: 9_000.0  # maximum value of the support
exploration_noise : 0.15  # standard deviation of the exploration noise
n_step: 5 # how many steps in the trajectory to use for the n-step return
