# ---Environment Configs---
env_name: jumanji
observation_attribute : grid
multi_agent : False

scenario:
  name: Sokoban-v0
  task_name: sokoban

kwargs: {}

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return


# Optional wrapper to flatten the observation space.
# wrapper:
#   _target_: stoix.wrappers.transforms.FlattenObservationWrapper
