# --- Defaults FF-MPO Discrete---

system_name: ff_mpo # Name of the system.

# --- RL hyperparameters ---
rollout_length: 8 # Number of environment steps per vectorised environment.
epochs: 16 # Number of sgd steps per rollout.
warmup_steps: 16  # Number of steps to collect before training.
total_buffer_size: 50_000 # Total effective size of the replay buffer across all devices and vectorised update steps. This means each device has a buffer of size buffer_size//num_devices which is further divided by the update_batch_size. This value must be divisible by num_devices*update_batch_size.
total_batch_size: 32 # Total effective number of samples to train on. This means each device has a batch size of batch_size/num_devices which is further divided by the update_batch_size. This value must be divisible by num_devices*update_batch_size.
sample_sequence_length: 8 # Number of steps to consider for each element of the batch.
period : 1 # Period of the sampled sequences.
actor_lr: 1e-4  # the learning rate of the policy network optimizer
q_lr: 1e-4  # the learning rate of the Q network network optimizer
dual_lr: 1e-2  # the learning rate of the alpha optimizer
tau: 0.005  # smoothing coefficient for target networks
gamma: 0.99  # discount factor
max_grad_norm: 40.0 # Maximum norm of the gradients for a weight update.
decay_learning_rates: False # Whether learning rates should be linearly decayed during training.
max_abs_reward : 20_000  # maximum absolute reward value
num_samples: 20 # Number of MPO action samples for the policy update.
epsilon: 0.01 # KL constraint on the non-parametric auxiliary policy, the one associated with the dual variable called temperature.
epsilon_policy : 1e-3 #  KL constraint on the categorical policy, the one associated with the dual variable called alpha.
init_log_temperature: 3. # initial value for the temperature in log-space, note a softplus (rather than an exp) will be used to transform this.
init_log_alpha: 3. # initial value for the alpha value in log-space, note a softplus (rather than an exp) will be used to transform this.
stochastic_policy_eval: True # whether to use a stochastic policy for Q function target evaluation.
use_online_policy_to_bootstrap: False # whether to use the online policy to bootstrap the Q function targets.
use_retrace : False # whether to use the retrace algorithm for off-policy correction.
retrace_lambda : 0.95 # the retrace lambda parameter.
use_n_step_bootstrap : False # whether to use n-step bootstrapping for the Q function targets.
n_step_for_sequence_bootstrap : 5 # the number of steps to use for the sequence bootstrap. This is only used if use_retrace is False and use_n_step_bootstrap is True.
gae_lambda : 0.95 # the GAE lambda parameter. This is only used if use_retrace is False and use_n_step_bootstrap is False.
