# ---Environment Configs---
env_name: craftax

scenario:
  name: Craftax-Classic-Pixels-v1
  task_name: classic_pixels

kwargs: {}

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return


# Optional wrapper to flatten the observation space.
wrapper:
  _target_: stoa.FlattenObservationWrapper

# Defines whether the optimistic reset wrapper should be used.
use_optimistic_reset: True
reset_ratio: 16
