# config.yaml
slurm:
  account: ~
  qos: ~
  nodes: 1
  gpus_per_node: 4
  cpus_per_task: 24
  partition: ~
  time: 00:60:00
  folder: "./slurm_logs"


experiment:
  algorithm_exec_files:
    - 'stoix/systems/impala/sebulba/ff_impala.py network=visual_resnet'
  environments: [envpool/breakout]
  seeds: [42]

experiment_group: example_group_run
