# config.yaml
slurm:
  account: ~
  qos: ~
  nodes: 1
  gpus_per_node: 1
  cpus_per_task: 24
  partition: ~
  time: 00:05:00
  folder: "./slurm_logs"


experiment:
  algorithm_exec_files:
    - 'stoix/systems/ppo/anakin/ff_ppo.py'
    - 'stoix/systems/ppo/anakin/rec_ppo.py'
  environments: [gymnax/cartpole, gymnax/mountain_car]
  seeds: [42]

experiment_group: example_group_run
