# ---Recurrent Structure Networks for PPO ---

actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  rnn_layer:
    _target_: stoix.networks.working_demov2.FFM
    trace_size: 16
    context_size: 16
    output_size: 256
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  action_head:
    _target_: stoix.networks.heads.CategoricalHead

critic_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  rnn_layer:
    _target_: stoix.networks.working_demov2.FFM
    trace_size: 16
    context_size: 16
    output_size: 256
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
