# ---Recurrent Structure Networks for PPO ---

actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: silu
  rnn_layer:
    _target_: stoix.networks.memoroid.ScannedMemoroid
    cell:
      _target_: stoix.networks.memoroid.MemoroidResetWrapper
      cell:
        _target_: stoix.networks.memoroid.FFMCell
        trace_size: 128
        context_size: 128
        output_size: 128
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: silu
  action_head:
    _target_: stoix.networks.heads.CategoricalHead

critic_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: silu
  rnn_layer:
    _target_: stoix.networks.memoroid.ScannedMemoroid
    cell:
      _target_: stoix.networks.memoroid.MemoroidResetWrapper
      cell:
        _target_: stoix.networks.memoroid.FFMCell
        trace_size: 128
        context_size: 128
        output_size: 128
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: silu
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
