# ---MLP Actor Critic Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256, 256]
    use_layer_norm: False
    activation: silu
  action_head:
    _target_: stoix.networks.heads.CategoricalHead

critic_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256, 256]
    use_layer_norm: False
    activation: silu
  critic_head:
    _target_: stoix.networks.heads.CategoricalCriticHead

# ---MLP MuZero Networks---
representation_network:
  torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256, 256]
    use_layer_norm: False
    activation: silu
  embedding_head:
    _target_: stoix.networks.heads.LinearHead
    output_dim: 128 # Output dimension of the embedding head. This should match the output dimension of the dynamics network.

dynamics_network:
  input_layer:
    _target_: stoix.networks.inputs.EmbeddingActionOnehotInput
  torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256, 256]
    use_layer_norm: False
    activation: silu
  embedding_head:
    _target_: stoix.networks.heads.LinearHead
    output_dim: 128 # Output dimension of the embedding head. This should match the output dimension of the representation network.
  reward_head:
    _target_: stoix.networks.heads.CategoricalCriticHead
