# ---Recurrent Structure Networks for PPO ---

actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: silu
  rnn_layer:
    _target_: stoix.networks.base.ScannedRNN
    cell_type: gru
    hidden_state_dim: 128
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: silu
  action_head:
    _target_: stoix.networks.heads.CategoricalHead

critic_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: silu
  rnn_layer:
    _target_: stoix.networks.base.ScannedRNN
    cell_type: gru
    hidden_state_dim: 128
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: silu
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
