# ---Recurrent Structure Networks for PPO ---

actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  rnn_layer:
    _target_: stoix.networks.s5.StackedEncoderModel
    ssm_size: 256
    d_model: 256
    n_layers: 1
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  action_head:
    _target_: stoix.networks.heads.CategoricalHead

critic_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  rnn_layer:
    _target_: stoix.networks.s5.StackedEncoderModel
    ssm_size: 256
    d_model: 256
    n_layers: 1
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
