# ---Recurrent Structure Networks for PPO ---

actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: True
    activation: leaky_relu
  rnn_layer:
    _target_: stoix.networks.memoroids.layers.StackedMemoroid
    num_cells: 2
    lrm_cell_type: ffm
    cell_kwargs:
      trace_size: 64
      context_size: 4
      output_size: 256
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  action_head:
    _target_: stoix.networks.heads.CategoricalHead

critic_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: True
    activation: leaky_relu
  rnn_layer:
    _target_: stoix.networks.memoroids.layers.StackedMemoroid
    num_cells: 2
    lrm_cell_type: ffm
    cell_kwargs:
      trace_size: 64
      context_size: 4
      output_size: 256
  post_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256]
    use_layer_norm: False
    activation: leaky_relu
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
