# ---ResNet---
actor_network:
  pre_torso:
    _target_: stoix.networks.resnet.VisualResNetTorso
    channels_per_group: [16, 32, 32]
    blocks_per_group: [2, 2, 2]
    use_layer_norm: False
    activation: silu
    channel_first: True
  action_head:
    _target_: stoix.networks.heads.CategoricalHead

critic_network:
  pre_torso:
    _target_: stoix.networks.resnet.VisualResNetTorso
    channels_per_group: [16, 32, 32]
    blocks_per_group: [2, 2, 2]
    use_layer_norm: False
    activation: silu
    channel_first: True
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
