# ---Environment Configs---
env_name: mpe

scenario:
  name: MPE_simple_v3
  task_name: mpe_simple

add_agent_ids_to_state: False # Adds the agent IDs to the global state.
add_global_state : False # Adds the global state to the observations.

kwargs:
  num_agents : 1

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return


# Optional wrapper to flatten the observation space.
wrapper:
  _target_: stoix.wrappers.transforms.FlattenObservationWrapper
