# ---Environment Configs---
env_name: smax
# Possible scenarios:
# 2s3z | 3s5z | 5m_vs_6m | 10m_vs_11m | 27m_vs_30m | 3s5z_vs_3s6z | 3s_vs_5z | 6h_vs_8z | smacv2_5_units | smacv2_10_units | smacv2_20_units
scenario:
  name: HeuristicEnemySMAX
  task_name: 2s3z

add_agent_ids_to_state: False # Adds the agent IDs to the global state.
add_global_state : False # Adds the global state to the observations.

kwargs:
  see_enemy_actions: True # Whether to enable enemy vision. If True, the enemy will be able to see the actions of the agent.
  walls_cause_death: True # Whether to kill the agent if it collides with a wall.
  attack_mode: "closest" # "closest" or "random". Whether to attack the closest enemy or a random enemy.

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return


# Optional wrapper to flatten the observation space.
wrapper:
  _target_: stoix.wrappers.transforms.FlattenObservationWrapper
