# ---MLP PPO Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.base.chained_torsos # we call the chained torsos creation function
    _recursive_: false # we disable recursive instantiation for this object as we do the creation manually
    torso_cfgs:
      - _target_: stoix.networks.specialised.kinetix.PermutationInvariantEntityEncoder
      - _target_: stoix.networks.torso.MLPTorso
        layer_sizes: [256, 256, 256]
        use_layer_norm: False
        activation: tanh
  action_head:
    _target_: stoix.networks.heads.MultiDiscreteHead
    number_of_dims_per_distribution: [3, 3, 3, 3, 2, 2]

critic_network:
  pre_torso:
    _target_: stoix.networks.base.chained_torsos # we call the chained torsos creation function
    _recursive_: false # we disable recursive instantiation for this object as we do the creation manually
    torso_cfgs:
      - _target_: stoix.networks.specialised.kinetix.PermutationInvariantEntityEncoder
      - _target_: stoix.networks.torso.MLPTorso
        layer_sizes: [256, 256, 256]
        use_layer_norm: False
        activation: tanh
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
