# ---MLP PPO Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.torso.CNNTorso
    channel_sizes: [32, 32]
    kernel_sizes: [3, 3]
    strides: [1, 1]
    use_layer_norm: False
    activation: tanh
    channel_first: True
    hidden_sizes: [128, 128]
  action_head:
    _target_: stoix.networks.heads.MultiDiscreteHead
    number_of_dims_per_distribution: [3, 3, 3, 3, 2, 2]

critic_network:
  pre_torso:
    _target_: stoix.networks.torso.CNNTorso
    channel_sizes: [32, 32]
    kernel_sizes: [3, 3]
    strides: [1, 1]
    use_layer_norm: False
    activation: tanh
    channel_first: True
    hidden_sizes: [128, 128]
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
