# ---Environment Configs---
env_name: xland_minigrid
scenario:
  name: MiniGrid-Empty-5x5
  task_name: minigrid_empty_5x5

kwargs: {}

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return


# Optional wrapper to flatten the observation space.
wrapper:
  _target_: stoix.wrappers.transforms.FlattenObservationWrapper
