# ---Environment Configs---
env_name: kinetix

defaults:
  - kinetix/eval: s
  - kinetix/train: s
  - _self_


scenario:
  name: Kinetix
  task_name: small
  action_type: multi_discrete
  observation_type: symbolic_entity



# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return
eval_reset_fn:
  _target_: stoix.wrappers.kinetix.make_kinetix_eval_reset_fn

solved_return_threshold: 0.6
