# --- Defaults FF-PPO ---

system_name: ff_ppo # Name of the system.

# --- RL hyperparameters ---
actor_lr: 3e-4 # Learning rate for actor network
critic_lr: 3e-4 # Learning rate for critic network
rollout_length: 128 # Number of environment steps per vectorised environment
epochs: 4 # Number of ppo epochs per training data batch.
num_minibatches: 16 # Number of minibatches per ppo epoch
gamma: 0.99 # Discounting factor.
gae_lambda: 0.95 # Lambda value for GAE computation.
clip_eps: 0.2 # Clipping value for PPO updates and value function
ent_coef: 0.01 # Entropy regularisation term for loss function
vf_coef: 0.5 # Critic weight
max_grad_norm: 0.5 # Maximum norm of the gradients for a weight update.
decay_learning_rates: True # Whether learning rates should be linearly decayed during training.
reward_scale: 1.0 # Scale factor for rewards, useful for environments with large reward magnitudes.
standardize_advantages: True # Whether to standardize the advantages.
kl_penalty_coef: 3.0 # KL penalty coefficient for PPO updates if using PPO Penalty.
normalize_observations: False # Whether to normalize observations using running statistics if observation normalisation is implemented.
obs_norm_warmup_steps: 128 # If normalising observations, number of warmup steps to collect observations for initial statistics = total_num_envs * obs_norm_warmup_steps.
