# ---Environment Configs---
env_name: navix
scenario:
  name: Navix-DoorKey-8x8-v0
  task_name: navix-door_key-8x8-v0

kwargs: {}

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return

# Optional wrapper to flatten the observation space.
wrapper:
  _target_: stoix.wrappers.transforms.FlattenObservationWrapper
